### ISSUE TITLE
jquery has deprecated synchronous XMLHTTPRequest

### ISSUE THREAD

**Issue by manueljordan** [jquery-i18n-properties/jquery-i18n-properties#25]
Hello

I am working with `jquery-i18n-properties` and I get how a warning the following messaging:

![error](https://cloud.githubusercontent.com/assets/2552795/12105545/cbad86e2-b323-11e5-9c71-9d779547f2c4.png)

The problem has been reported here:
[jquery has deprecated synchronous XMLHTTPRequest](http://stackoverflow.com/questions/27736186/jquery-has-deprecated-synchronous-xmlhttprequest)

Check the following [answer](http://stackoverflow.com/a/27736383/3665178) (mostly check the comments)

Thanks.

**Comment by manueljordan** [comment]
It has been fixed?
I am on: https://github.com/jquery-i18n-properties/jquery-i18n-properties
I can see the latest file is `jquery.i18n.properties.js` I have used that and I have the same warning yet.

**Comment by adrianfish** [comment]
Check out the README.md, under Asynchronous Language Loading. You need to add the flag async: true to the settings that you pass through. You also need to make sure that you implement your code that  uses the loaded languages in the callback, otherwise your code will run past the language load and will fail.
